name: Portfolio-dev
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3
    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Instalar dependencias
      run: npm install
    - name: Construir y probar
      run: npm test
